In [1]:
import numpy as np
np.__version__

'1.20.3'

In [2]:
import pandas as pd

data = pd.read_csv('data.csv')

In [3]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [4]:
data.shape

(11914, 16)

In [5]:
new_data = pd.DataFrame(data.groupby(['Make'])['Make'].count())

In [6]:
new_data.head()

Make
Make              
Acura          252
Alfa Romeo       5
Aston Martin    93
Audi           328
BMW            334

In [7]:
new_data.rename(columns ={'Make':'count'}, inplace = True)

In [8]:
new_data.sort_values(by = 'count', ascending = False)

count
Make                
Chevrolet       1123
Ford             881
Volkswagen       809
Toyota           746
Dodge            626
Nissan           558
GMC              515
Honda            449
Mazda            423
Cadillac         397
Mercedes-Benz    353
Suzuki           351
BMW              334
Infiniti         330
Audi             328
Hyundai          303
Volvo            281
Subaru           256
Acura            252
Kia              231
Mitsubishi       213
Lexus            202
Buick            196
Chrysler         187
Pontiac          186
Lincoln          164
Oldsmobile       150
Land Rover       143
Porsche          136
Saab             111
Aston Martin      93
Plymouth          82
Bentley           74
Ferrari           69
FIAT              62
Scion             60
Maserati          58
Lamborghini       52
Rolls-Royce       31
Lotus             29
Tesla             18
HUMMER            17
Maybach           16
McLaren            5
Alfa Romeo         5
Spyker             3
Bugatti            3
Genesis            3

In [9]:
data[data['Make'] == 'Audi'].nunique()

Make                   1
Model                 34
Year                  20
Engine Fuel Type       5
Engine HP             40
Engine Cylinders       6
Transmission Type      3
Driven_Wheels          2
Number of Doors        2
Market Category       15
Vehicle Size           3
Vehicle Style          6
highway MPG           23
city mpg              18
Popularity             1
MSRP                 234
dtype: int64

In [10]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [11]:
data['Engine Cylinders'].median()

6.0

In [12]:
data.groupby(['Engine Cylinders'])['Engine Cylinders'].count()

Engine Cylinders
0.0       56
3.0       30
4.0     4752
5.0      225
6.0     4489
8.0     2031
10.0      68
12.0     230
16.0       3
Name: Engine Cylinders, dtype: int64

In [13]:
data['Engine Cylinders'] = data['Engine Cylinders'].fillna(4.0)

In [14]:
data['Engine Cylinders'].median()

6.0

In [15]:
data.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders        0
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [16]:
data[data['Make'] == 'Lotus'].nunique()

Make                  1
Model                 5
Year                  9
Engine Fuel Type      2
Engine HP             9
Engine Cylinders      3
Transmission Type     1
Driven_Wheels         1
Number of Doors       1
Market Category       1
Vehicle Size          1
Vehicle Style         2
highway MPG           4
city mpg              5
Popularity            1
MSRP                 23
dtype: int64

In [28]:
data2 = pd.DataFrame(data.loc[data['Make'] == 'Lotus',['Engine HP', 'Engine Cylinders']]).drop_duplicates()

In [29]:
X = data2.to_numpy()

In [30]:
X_trans = np.transpose(X)

In [31]:
X_trans

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [32]:
XTX = np.dot(X_trans, X)

In [33]:
inverse = np.linalg.inv(XTX)

In [34]:
inverse

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [35]:
Y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])

In [36]:
mult_1 = np.dot(inverse, X_trans)

In [37]:
w = np.dot(mult_1, Y)

In [38]:
w

array([  4.59494481, -63.56432501])